// Code generated by protoc-gen-go.
// source: comment.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	comment.proto
	diary.proto
	dream.proto
	feedback.proto
	nulltype.proto
	photo.proto
	photoechooption.proto
	queryparameter.proto
	user.proto

It has these top-level messages:
	Comment
	Diary
	Empty
	IncrementRequest
	Users
	PostUserRequest
	UserResponse
	PostAccountRequest
	PutUserByIDRequest
	PutUserByUUIDRequest
	PutUserPasswordRequest
	GetByIDRequest
	GetUserByTusoIDRequest
	GetByUUIDRequest
	GetUserByMobileRequest
	GetUserByEmailRequest
	GetByIDsRequest
	GetByUUIDsRequest
	GetUserByMobilesRequest
	FindUserRequest
	Bool
	PhoneRequest
	SockpuppetRequest
	UserRelationRequest
	UserRelations
	PostRelationRequest
	RelationResponse
	FindByIDWithQPRequest
	GetRelationRequest
	UserRelationTypeResponse
	Comments
	PostCommentRequest
	CommentResponse
	FindPCWithoutOwnerRequest
	FindPhotoReplyRequest
	FirstCommentRequest
	PostDiaryRequest
	DiaryResponse
	DiaryByIDRequest
	Diaries
	FindByUUIDWithQPRequest
	PostFeedbackRequest
	NoteResponse
	PostNoteRequest
	Notes
	NoteByIDRequest
	NoteByUUIDRequest
	PhotoWithEchoOptionRequest
	PhotoResponse
	PhotoWithUUIDRequest
	PhotoWithIDRequest
	IDAndUUIDWithEchoOptionRequest
	UUIDAndVersionWithPhotoRequest
	Photos
	UUIDsWithEchoOptionRequest
	IDsWithEchoOptionRequest
	IDWithEchoOptionRequest
	UUIDWithEchoOptionRequest
	UUIDWithIdentifierRequest
	UUIDWithOptionRequest
	IDWithOptionRequest
	PostFileRequest
	FileResponse
	FileWithIDRequest
	FileWithUUIDRequest
	FileWithPIDRequest
	Files
	Feedback
	StringType
	IntegerType
	BooleanType
	BasePhoto
	Photo
	Note
	File
	PhotoEchoOption
	QueryParameter
	PageModel
	User
	UserRelation
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type CommentType int32

const (
	CommentType_comment_type_null  CommentType = 0
	CommentType_comment_type_news  CommentType = 1
	CommentType_comment_type_image CommentType = 2
	CommentType_comment_type_diary CommentType = 3
)

var CommentType_name = map[int32]string{
	0: "comment_type_null",
	1: "comment_type_news",
	2: "comment_type_image",
	3: "comment_type_diary",
}
var CommentType_value = map[string]int32{
	"comment_type_null":  0,
	"comment_type_news":  1,
	"comment_type_image": 2,
	"comment_type_diary": 3,
}

func (x CommentType) String() string {
	return proto1.EnumName(CommentType_name, int32(x))
}
func (CommentType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Comment struct {
	ID          int64       `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	UUID        string      `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	SourceId    int64       `protobuf:"varint,3,opt,name=SourceId,json=sourceId" json:"SourceId,omitempty"`
	User        *User       `protobuf:"bytes,4,opt,name=User,json=user" json:"User,omitempty"`
	UserUUID    string      `protobuf:"bytes,5,opt,name=UserUUID,json=userUUID" json:"UserUUID,omitempty"`
	ReplyTo     *Comment    `protobuf:"bytes,6,opt,name=ReplyTo,json=replyTo" json:"ReplyTo,omitempty"`
	ReplyToUUID string      `protobuf:"bytes,7,opt,name=ReplyToUUID,json=replyToUUID" json:"ReplyToUUID,omitempty"`
	Content     string      `protobuf:"bytes,8,opt,name=Content,json=content" json:"Content,omitempty"`
	Type        CommentType `protobuf:"varint,9,opt,name=Type,json=type,enum=proto.CommentType" json:"Type,omitempty"`
	Timestamp   string      `protobuf:"bytes,10,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
}

func (m *Comment) Reset()                    { *m = Comment{} }
func (m *Comment) String() string            { return proto1.CompactTextString(m) }
func (*Comment) ProtoMessage()               {}
func (*Comment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Comment) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Comment) GetReplyTo() *Comment {
	if m != nil {
		return m.ReplyTo
	}
	return nil
}

func init() {
	proto1.RegisterType((*Comment)(nil), "proto.Comment")
	proto1.RegisterEnum("proto.CommentType", CommentType_name, CommentType_value)
}

func init() { proto1.RegisterFile("comment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x4f, 0x4f, 0x83, 0x40,
	0x10, 0xc5, 0x2d, 0xd0, 0x02, 0x43, 0x24, 0x38, 0x89, 0x66, 0xd3, 0x98, 0xd8, 0x78, 0x30, 0x8d,
	0x87, 0x1e, 0xea, 0x47, 0xb0, 0x97, 0x5e, 0x91, 0x9e, 0x1b, 0xa4, 0x1b, 0x43, 0xe4, 0x5f, 0x96,
	0x25, 0x86, 0xaf, 0xe5, 0x27, 0x74, 0x76, 0x58, 0xa3, 0x4d, 0x2f, 0x0b, 0xef, 0x37, 0xef, 0xbd,
	0x1d, 0x80, 0xeb, 0xa2, 0xad, 0x6b, 0xd9, 0xe8, 0x4d, 0xa7, 0x5a, 0xdd, 0xe2, 0x9c, 0x1f, 0x4b,
	0x18, 0x7a, 0xa9, 0x26, 0xf4, 0xf8, 0xed, 0x80, 0xff, 0x3a, 0x99, 0x30, 0x06, 0x67, 0xbf, 0x13,
	0xb3, 0xd5, 0x6c, 0xed, 0xa6, 0x4e, 0xb9, 0x43, 0x04, 0xef, 0x70, 0x20, 0xe2, 0x10, 0x09, 0x53,
	0x6f, 0xa0, 0x77, 0x5c, 0x42, 0xf0, 0xd6, 0x0e, 0xaa, 0x90, 0xfb, 0x93, 0x70, 0xd9, 0x19, 0xf4,
	0x56, 0xe3, 0x03, 0xf9, 0xa9, 0x59, 0x78, 0xc4, 0xa3, 0x6d, 0x34, 0xdd, 0xb0, 0x31, 0x88, 0xc2,
	0x74, 0x9a, 0xb0, 0x51, 0x5c, 0x3a, 0xe7, 0xd2, 0x60, 0xb0, 0x1a, 0xd7, 0xe0, 0xa7, 0xb2, 0xab,
	0xc6, 0xac, 0x15, 0x0b, 0xce, 0xc7, 0x36, 0x6f, 0xb7, 0x4b, 0x7d, 0x35, 0x8d, 0x71, 0x05, 0x91,
	0x75, 0x72, 0x91, 0xcf, 0x45, 0x91, 0xfa, 0x43, 0x28, 0xcc, 0x37, 0x35, 0x9a, 0x52, 0x22, 0xe0,
	0xa9, 0x5f, 0x4c, 0x12, 0x9f, 0xc0, 0xcb, 0xc6, 0x4e, 0x8a, 0x90, 0x70, 0xbc, 0xc5, 0xf3, 0x2b,
	0xcc, 0x24, 0xf5, 0x34, 0x9d, 0x78, 0x0f, 0x61, 0x56, 0xd6, 0xb2, 0xd7, 0x79, 0xdd, 0x09, 0xe0,
	0x8e, 0x50, 0xff, 0x82, 0xe7, 0x4f, 0x88, 0xfe, 0x45, 0xf0, 0x16, 0x6e, 0xec, 0x7f, 0x3e, 0x9a,
	0xf0, 0xb1, 0x19, 0xaa, 0x2a, 0xb9, 0xba, 0xc4, 0xf2, 0xab, 0x4f, 0x66, 0x78, 0x07, 0x78, 0x86,
	0xcb, 0x3a, 0xff, 0x90, 0x89, 0x73, 0xc1, 0x4f, 0x65, 0xae, 0xc6, 0xc4, 0x7d, 0x5f, 0xf0, 0x8e,
	0x2f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x70, 0x1c, 0x9e, 0x9a, 0xcc, 0x01, 0x00, 0x00,
}
