// Code generated by protoc-gen-go.
// source: athena.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	athena.proto
	comment.proto
	diary.proto
	dream.proto
	feedback.proto
	notice.proto
	nulltype.proto
	photo.proto
	photoechooption.proto
	queryparameter.proto
	user.proto

It has these top-level messages:
	News
	AllUserNewsRequest
	AllUserNewsResponse
	Comment
	Diary
	Empty
	IncrementRequest
	Users
	PostUserRequest
	UserResponse
	PostAccountRequest
	PutUserByIDRequest
	PutUserByUUIDRequest
	PutUserPasswordRequest
	GetByIDRequest
	GetUserByTusoIDRequest
	GetByUUIDRequest
	GetUserByMobileRequest
	GetUserByEmailRequest
	GetByIDsRequest
	GetByUUIDsRequest
	GetUserByMobilesRequest
	FindUserRequest
	Bool
	PhoneRequest
	SockpuppetRequest
	AllUserAllRelationRequest
	AllUserAllRelationResponse
	UserRelations
	PostRelationRequest
	RelationResponse
	FindByIDWithQPRequest
	GetRelationRequest
	UserRelationTypeResponse
	Comments
	PostCommentRequest
	CommentResponse
	FindPCWithoutOwnerRequest
	FindPhotoReplyRequest
	FirstCommentRequest
	PostDiaryRequest
	DiaryResponse
	DiaryByIDRequest
	Diaries
	FindByUUIDWithQPRequest
	PostFeedbackRequest
	NoteResponse
	PostNoteRequest
	Notes
	NoteByIDRequest
	NoteByUUIDRequest
	PhotoWithEchoOptionRequest
	PhotoResponse
	PhotoWithUUIDRequest
	PhotoWithIDRequest
	IDAndUUIDWithEchoOptionRequest
	UUIDAndVersionWithPhotoRequest
	Photos
	UUIDsWithEchoOptionRequest
	IDsWithEchoOptionRequest
	IDWithEchoOptionRequest
	UUIDWithEchoOptionRequest
	UUIDWithIdentifierRequest
	UUIDWithOptionRequest
	IDWithOptionRequest
	PostFileRequest
	FileResponse
	FileWithIDRequest
	FileWithUUIDRequest
	FileWithPIDRequest
	Files
	Feedback
	Notice
	StringType
	IntegerType
	BooleanType
	BasePhoto
	Photo
	Note
	File
	PhotoEchoOption
	QueryParameter
	PageModel
	User
	UserRelation
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type News struct {
	ID           int64    `protobuf:"varint,1,opt,name=ID,json=iD" json:"ID,omitempty"`
	UUID         string   `protobuf:"bytes,2,opt,name=UUID,json=uUID" json:"UUID,omitempty"`
	CreatedAt    string   `protobuf:"bytes,3,opt,name=CreatedAt,json=createdAt" json:"CreatedAt,omitempty"`
	UpdatedAt    string   `protobuf:"bytes,4,opt,name=UpdatedAt,json=updatedAt" json:"UpdatedAt,omitempty"`
	DeletedAt    string   `protobuf:"bytes,5,opt,name=DeletedAt,json=deletedAt" json:"DeletedAt,omitempty"`
	UserID       int64    `protobuf:"varint,6,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	PhotoIDs     []int64  `protobuf:"varint,7,rep,name=PhotoIDs,json=photoIDs" json:"PhotoIDs,omitempty"`
	PhotoCount   int64    `protobuf:"varint,8,opt,name=PhotoCount,json=photoCount" json:"PhotoCount,omitempty"`
	CommentCount int64    `protobuf:"varint,9,opt,name=CommentCount,json=commentCount" json:"CommentCount,omitempty"`
	StarredCount int64    `protobuf:"varint,10,opt,name=StarredCount,json=starredCount" json:"StarredCount,omitempty"`
	Timestamp    string   `protobuf:"bytes,11,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	User         *User    `protobuf:"bytes,12,opt,name=User,json=user" json:"User,omitempty"`
	Photos       []*Photo `protobuf:"bytes,13,rep,name=Photos,json=photos" json:"Photos,omitempty"`
}

func (m *News) Reset()                    { *m = News{} }
func (m *News) String() string            { return proto1.CompactTextString(m) }
func (*News) ProtoMessage()               {}
func (*News) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *News) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *News) GetPhotos() []*Photo {
	if m != nil {
		return m.Photos
	}
	return nil
}

type AllUserNewsRequest struct {
	OffsetHead int64  `protobuf:"varint,1,opt,name=offsetHead" json:"offsetHead,omitempty"`
	OffsetTail int64  `protobuf:"varint,2,opt,name=offsetTail" json:"offsetTail,omitempty"`
	StartTime  string `protobuf:"bytes,3,opt,name=startTime" json:"startTime,omitempty"`
	EndTime    string `protobuf:"bytes,4,opt,name=endTime" json:"endTime,omitempty"`
}

func (m *AllUserNewsRequest) Reset()                    { *m = AllUserNewsRequest{} }
func (m *AllUserNewsRequest) String() string            { return proto1.CompactTextString(m) }
func (*AllUserNewsRequest) ProtoMessage()               {}
func (*AllUserNewsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AllUserNewsResponse struct {
	Count    int64   `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
	TusoList []*News `protobuf:"bytes,2,rep,name=tusoList" json:"tusoList,omitempty"`
}

func (m *AllUserNewsResponse) Reset()                    { *m = AllUserNewsResponse{} }
func (m *AllUserNewsResponse) String() string            { return proto1.CompactTextString(m) }
func (*AllUserNewsResponse) ProtoMessage()               {}
func (*AllUserNewsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AllUserNewsResponse) GetTusoList() []*News {
	if m != nil {
		return m.TusoList
	}
	return nil
}

func init() {
	proto1.RegisterType((*News)(nil), "proto.News")
	proto1.RegisterType((*AllUserNewsRequest)(nil), "proto.AllUserNewsRequest")
	proto1.RegisterType((*AllUserNewsResponse)(nil), "proto.AllUserNewsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AthenaServices service

type AthenaServicesClient interface {
	GetAllUserNews(ctx context.Context, in *AllUserNewsRequest, opts ...client.CallOption) (*AllUserNewsResponse, error)
}

type athenaServicesClient struct {
	c           client.Client
	serviceName string
}

func NewAthenaServicesClient(serviceName string, c client.Client) AthenaServicesClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto"
	}
	return &athenaServicesClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *athenaServicesClient) GetAllUserNews(ctx context.Context, in *AllUserNewsRequest, opts ...client.CallOption) (*AllUserNewsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AthenaServices.GetAllUserNews", in)
	out := new(AllUserNewsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AthenaServices service

type AthenaServicesHandler interface {
	GetAllUserNews(context.Context, *AllUserNewsRequest, *AllUserNewsResponse) error
}

func RegisterAthenaServicesHandler(s server.Server, hdlr AthenaServicesHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AthenaServices{hdlr}, opts...))
}

type AthenaServices struct {
	AthenaServicesHandler
}

func (h *AthenaServices) GetAllUserNews(ctx context.Context, in *AllUserNewsRequest, out *AllUserNewsResponse) error {
	return h.AthenaServicesHandler.GetAllUserNews(ctx, in, out)
}

func init() { proto1.RegisterFile("athena.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x8e, 0xd3, 0x40,
	0x0c, 0x87, 0x69, 0xd3, 0x66, 0x5b, 0x27, 0xf4, 0x60, 0x10, 0x1a, 0x22, 0x04, 0xab, 0x08, 0x09,
	0x4e, 0x7b, 0x28, 0x4f, 0x50, 0xb5, 0x12, 0x54, 0x42, 0x08, 0x75, 0xdb, 0x13, 0xa7, 0x90, 0x78,
	0xd5, 0x48, 0xf9, 0x47, 0x66, 0x02, 0x4f, 0xc0, 0x8d, 0x87, 0xc6, 0xe3, 0x49, 0x42, 0x10, 0x5c,
	0x36, 0xeb, 0xef, 0xf3, 0x68, 0x7e, 0x63, 0x17, 0xc2, 0xc4, 0x5c, 0xa9, 0x4a, 0xee, 0x9a, 0xb6,
	0x36, 0x35, 0x2e, 0xe5, 0x13, 0x41, 0xa7, 0xa9, 0x75, 0x28, 0x0a, 0x9a, 0x2b, 0x7f, 0x5c, 0x11,
	0xff, 0xf4, 0x60, 0xf1, 0x89, 0x7e, 0x68, 0xdc, 0xc0, 0xfc, 0x78, 0x50, 0xb3, 0xdb, 0xd9, 0x5b,
	0xef, 0x34, 0xcf, 0x0f, 0x88, 0xb0, 0xb8, 0x5c, 0x98, 0xcc, 0x99, 0xac, 0x4f, 0x8b, 0x8e, 0xff,
	0xc7, 0x17, 0xb0, 0xde, 0xb7, 0x94, 0x18, 0xca, 0x76, 0x46, 0x79, 0x22, 0xd6, 0xe9, 0x00, 0xac,
	0xbd, 0x34, 0x59, 0x6f, 0x17, 0xce, 0x76, 0x03, 0xb0, 0xf6, 0x40, 0x05, 0x39, 0xbb, 0x74, 0x36,
	0x1b, 0x00, 0x3e, 0x03, 0xff, 0xc2, 0x09, 0xf9, 0x3e, 0x5f, 0x12, 0xf8, 0x9d, 0x54, 0x18, 0xc1,
	0xea, 0xb3, 0x4d, 0x7b, 0x3c, 0x68, 0x75, 0x73, 0xeb, 0xb1, 0x59, 0x35, 0x7d, 0x8d, 0x2f, 0x01,
	0xc4, 0xed, 0xeb, 0xae, 0x32, 0x6a, 0x25, 0xe7, 0xa0, 0x19, 0x09, 0xc6, 0x10, 0xee, 0xeb, 0xb2,
	0xa4, 0xca, 0xb8, 0x8e, 0xb5, 0x74, 0x84, 0xe9, 0x84, 0xd9, 0x9e, 0x7b, 0x93, 0xb4, 0x2d, 0x65,
	0xae, 0x07, 0x5c, 0x8f, 0x9e, 0x30, 0x9b, 0xfc, 0x9c, 0x97, 0xc4, 0xac, 0x6c, 0x54, 0xe0, 0x92,
	0x9b, 0x01, 0xe0, 0x2b, 0x9e, 0x13, 0x67, 0x55, 0x21, 0x8b, 0x60, 0x1b, 0xb8, 0xb1, 0xde, 0x59,
	0xc4, 0x43, 0xe3, 0xbf, 0xf8, 0x1a, 0x7c, 0x89, 0xa9, 0xd5, 0x63, 0x7e, 0x40, 0xb0, 0x0d, 0xfb,
	0x16, 0x81, 0x27, 0x5f, 0x02, 0xeb, 0xf8, 0xd7, 0x0c, 0x70, 0x57, 0x14, 0xf6, 0x9c, 0x5d, 0xc7,
	0x89, 0xbe, 0x75, 0x7c, 0x81, 0x7d, 0x63, 0xfd, 0xf0, 0xa0, 0xc9, 0x7c, 0xa0, 0x24, 0xeb, 0xb7,
	0x33, 0x21, 0x7f, 0xfc, 0x39, 0xc9, 0x0b, 0xd9, 0xd5, 0xe8, 0x2d, 0xb1, 0xd9, 0xed, 0x5b, 0x8c,
	0x7d, 0xc0, 0xb0, 0xb1, 0x11, 0xa0, 0x82, 0x1b, 0xaa, 0x32, 0x71, 0x6e, 0x5f, 0x43, 0x19, 0x9f,
	0xe1, 0xc9, 0x5f, 0x69, 0x74, 0x53, 0x57, 0x9a, 0xf0, 0x29, 0x2c, 0x53, 0x99, 0x93, 0x4b, 0xe2,
	0x0a, 0x7c, 0x03, 0x2b, 0xd3, 0xe9, 0xfa, 0x63, 0xae, 0x0d, 0x47, 0xf0, 0x26, 0x63, 0x90, 0xc3,
	0xa3, 0xdc, 0x7e, 0x81, 0xcd, 0x4e, 0x7e, 0x9c, 0xf7, 0xd4, 0x7e, 0xcf, 0x53, 0xd2, 0x78, 0x84,
	0xcd, 0x7b, 0x32, 0x93, 0xab, 0xf0, 0x79, 0x7f, 0xf4, 0xdf, 0x61, 0x44, 0xd1, 0xff, 0x94, 0x4b,
	0x16, 0x3f, 0xfa, 0xea, 0x8b, 0x7c, 0xf7, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xed, 0x1b, 0x36, 0xbc,
	0x00, 0x03, 0x00, 0x00,
}
