// Code generated by protoc-gen-go.
// source: nulltype.proto
// DO NOT EDIT!

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type StringType struct {
	String_ string `protobuf:"bytes,1,opt,name=String,json=string" json:"String,omitempty"`
	Null    bool   `protobuf:"varint,2,opt,name=Null,json=null" json:"Null,omitempty"`
}

func (m *StringType) Reset()                    { *m = StringType{} }
func (m *StringType) String() string            { return proto1.CompactTextString(m) }
func (*StringType) ProtoMessage()               {}
func (*StringType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

type IntegerType struct {
	Int  int64 `protobuf:"varint,1,opt,name=Int,json=int" json:"Int,omitempty"`
	Null bool  `protobuf:"varint,2,opt,name=Null,json=null" json:"Null,omitempty"`
}

func (m *IntegerType) Reset()                    { *m = IntegerType{} }
func (m *IntegerType) String() string            { return proto1.CompactTextString(m) }
func (*IntegerType) ProtoMessage()               {}
func (*IntegerType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

type BooleanType struct {
	Bool bool `protobuf:"varint,1,opt,name=Bool,json=bool" json:"Bool,omitempty"`
	Null bool `protobuf:"varint,2,opt,name=Null,json=null" json:"Null,omitempty"`
}

func (m *BooleanType) Reset()                    { *m = BooleanType{} }
func (m *BooleanType) String() string            { return proto1.CompactTextString(m) }
func (*BooleanType) ProtoMessage()               {}
func (*BooleanType) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{2} }

func init() {
	proto1.RegisterType((*StringType)(nil), "proto.StringType")
	proto1.RegisterType((*IntegerType)(nil), "proto.IntegerType")
	proto1.RegisterType((*BooleanType)(nil), "proto.BooleanType")
}

func init() { proto1.RegisterFile("nulltype.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2b, 0xcd, 0xc9,
	0x29, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x16,
	0x5c, 0x5c, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x21, 0x40, 0x29, 0x21, 0x31, 0x2e, 0x36, 0x08,
	0x4f, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x88, 0xad, 0x18, 0xcc, 0x13, 0x12, 0xe2, 0x62, 0xf1,
	0x03, 0x6a, 0x97, 0x60, 0x02, 0x8a, 0x72, 0x04, 0xb1, 0x80, 0x8c, 0x52, 0x32, 0xe6, 0xe2, 0xf6,
	0xcc, 0x2b, 0x49, 0x4d, 0x4f, 0x2d, 0x02, 0x6b, 0x15, 0xe0, 0x62, 0x06, 0x72, 0xc1, 0xfa, 0x98,
	0x83, 0x98, 0x33, 0xf3, 0x4a, 0xb0, 0x6a, 0x32, 0xe5, 0xe2, 0x76, 0xca, 0xcf, 0xcf, 0x49, 0x4d,
	0xcc, 0x03, 0x6b, 0x02, 0x2a, 0x01, 0x71, 0xc1, 0xba, 0x80, 0x4a, 0x92, 0x80, 0x6c, 0x6c, 0xda,
	0x92, 0xd8, 0xc0, 0x8e, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xbb, 0x4d, 0xd6, 0xc5,
	0x00, 0x00, 0x00,
}
