FROM consul:latest

# By default you'll get a single-node development server that stores everything
# in RAM, exposes a web UI, and bootstraps itself. Don't use this configuration
# for production.
# CMD ["agent", "-dev", "-ui"]