config:
  port: '10020'

diexin:
  url: 'http://sms.airlead.net:28080/chif10/mtsms'
  username: 'quxun'
  userpass: 'quxun'

downstream:
  '700271':
    back_url: 'http://192.168.1.159:8902/callback/quxun'
    template: '【自由充】您充值的{packet_name}已经提交成功，具体到账时间以运营商通知为准，有效期截至{end_time}。'
    offer_list:
      'TBM00000100A': '10M通用流量'
      'TBM00000300A': '30M通用流量'
      'TBM00000700A': '70M通用流量'
      'TBM00001500A': '150M通用流量'
      'TBM00005000A': '500M通用流量'
      'TBM00010000A': '1G通用流量'
      'TBM00020000A': '2G通用流量'
      'TBM00030000A': '3G通用流量'
      'TBM00040000A': '4G通用流量'
      'TBM00060000A': '6G通用流量'
      'TBM00110000A': '11G通用流量'
      'TBM00000100A': '10M通用流量'
      'TBM00000300A': '30M通用流量'
      'TBM00000700A': '70M通用流量'
      'TBM00001500A': '150M通用流量'
      'TBM00005000A': '500M通用流量'
      'TBM00010000A': '1G通用流量'
      'TBM00020000A': '2G通用流量'
      'TBM00030000A': '3G通用流量'
      'TBM00040000A': '4G通用流量'
      'TBM00060000A': '6G通用流量'
      'TBM00110000A': '11G通用流量'
      'TBU00000200A': '20M流量包'
      'TBU00000500A': '50M流量包'
      'TBU00001000A': '100M流量包'
      'TBU00002000A': '200M流量包'
      'TBU00005000A': '500M流量包'
      'TBU00010000A': '1G流量包'
      'TBC00000050B': '5M流量包'
      'TBC00000100B': '10M流量包'
      'TBC00000300B': '30M流量包'
      'TBC00000500B': '50M流量包'
      'TBC00001000B': '100M流量包'
      'TBC00002000B': '200M流量包'
      'TBC00005000B': '500M流量包'
      'TBC00010000B': '1G流量包'
    area_list:
      - '1:BJ'  #'北京',
      - '1:TJ'  #'天津',
      - '1:HE'  #'河北',
      - '1:SX'  #'山西',
      - '1:NM'  #'内蒙古',
      - '1:LN'  #'辽宁',
      - '1:JL'  #'吉林',
      - '1:HL'  #'黑龙江',
      - '1:SH'  #'上海',
      - '1:JS'  #'江苏',
      - '1:ZJ'  #'浙江',
      - '1:AH'  #'安徽',
      - '1:FJ'  #'福建',
      - '1:JX'  #'江西',
      - '1:SD'  #'山东',
      - '1:HA'  #'河南',
      - '1:HB'  #'湖北',
      - '1:HN'  #'湖南',
      - '1:GX'  #'广西',
      - '1:HI'  #'海南',
      - '1:CQ'  #'重庆',
      - '1:SC'  #'四川',
      - '1:GZ'  #'贵州',
      - '1:YN'  #'云南',
      - '1:XZ'  #'西藏',
      - '1:SN'  #'陕西',
      - '1:GS'  #'甘肃',
      - '1:QH'  #'青海',
      - '1:NX'  #'宁夏',
      - '1:XJ'  #'新疆',
      - '1:TW'  #'台湾',
      - '1:HK'  #'香港',
      - '1:CN'  #'全国'
      - '2:AH'  #'安徽',

  '700353':
    back_url: 'http://chongzhi.ruiputech.com/CorpInt/qxll/orderNotify.jsp'
    template: '【鼎诚生活宝】您充值的{packet_name}通用流量已经成功提交，请联系运营商确认生效情况！如有疑问，请联系鼎诚生活宝客服！'
    offer_list:
      'TBM00000100A': '10M'
      'TBM00000300A': '30M'
      'TBM00000700A': '70M'
      'TBM00001500A': '150M'
      'TBM00005000A': '500M'
      'TBM00010000A': '1G'
      'TBM00020000A': '2G'
      'TBM00030000A': '3G'
      'TBM00040000A': '4G'
      'TBM00060000A': '6G'
      'TBM00110000A': '11G'
    area_list:
      - '1:BJ'  #'北京',
      - '1:TJ'  #'天津',
      - '1:HE'  #'河北',
      - '1:SX'  #'山西',
      - '1:NM'  #'内蒙古',
      - '1:LN'  #'辽宁',
      - '1:JL'  #'吉林',
      - '1:HL'  #'黑龙江',
      - '1:SH'  #'上海',
      - '1:JS'  #'江苏',
      - '1:ZJ'  #'浙江',
      - '1:AH'  #'安徽',
      - '1:FJ'  #'福建',
      - '1:JX'  #'江西',
      - '1:SD'  #'山东',
      - '1:HA'  #'河南',
      - '1:HB'  #'湖北',
      - '1:HN'  #'湖南',
      - '1:GD'  #'广东',
      - '1:GX'  #'广西',
      - '1:HI'  #'海南',
      - '1:CQ'  #'重庆',
      - '1:SC'  #'四川',
      - '1:GZ'  #'贵州',
      - '1:YN'  #'云南',
      - '1:XZ'  #'西藏',
      - '1:SN'  #'陕西',
      - '1:GS'  #'甘肃',
      - '1:QH'  #'青海',
      - '1:NX'  #'宁夏',
      - '1:XJ'  #'新疆',
      - '1:TW'  #'台湾',
      - '1:HK'  #'香港',
      - '1:CN'  #'全国'
